// Generated by /home/claude/bdmap/build_api_deals.py from data/deals.json. Do not edit by hand.
export const DEALS = {
 "sylhet-sadapathor": {
  "op": "poribrajok",
  "code": "GD-SYL",
  "title": "সিলেট: সাদাপাথর, ভোলাগঞ্জ, রাতারগুল আর চা বাগান",
  "price": 1350
 },
 "sreemangal-day": {
  "op": "poribrajok",
  "code": "GD-SRI",
  "title": "শ্রীমঙ্গল: লাউয়াছড়া, মাধবপুর লেক আর চা বাগান",
  "price": 1550
 }
};
